### ISSUE TITLE
`ItemNameAdapter18` issue on MC 1.18.1

### ISSUE THREAD

**Issue by TheBusyBiscuit** [baked-libs/dough#106]
https://pastebin.com/4Mnz5ZER

**Comment by WalshyDev** [comment]
It looks like it's still getDisplayName on Spigot 1.18.1
![image](https://user-images.githubusercontent.com/8492901/146592378-58a4c3a4-6da4-464d-892c-d6cfd51dfb42.png)

**Comment by TheBusyBiscuit** [comment]
Yeah but why can the method not be found

**Comment by WalshyDev** [comment]
It's found for me. I had no issues.

**Comment by TheBusyBiscuit** [comment]
Did you test this branch?
https://github.com/Slimefun/Slimefun4/pull/3369

**Comment by WalshyDev** [comment]
Yep, using commit f0bf6f0d1d24024671aebd3c3021a15cdb5819fd

**Comment by TheBusyBiscuit** [comment]
weird.
What did you do to trigger this method?

**Comment by WalshyDev** [comment]
Ok, hadn't done too much. Yeah... got it to fire on the pedestal. That's weird...

I can debug it in ~30-60 mins

**Comment by TheBusyBiscuit** [comment]
> Yeah... got it to fire on the pedestal. That's weird...

Exactly! I'm not really getting why.

> I can debug it in ~30-60 mins

Thanks!
