### ISSUE TITLE
Residence slimefun error

### ISSUE THREAD

**Issue by DaliborTrampota** [baked-libs/dough#128]
## Description (Required)
Error log, ancient altar cant be used

## Steps to reproduce the Issue (Required)
no idea

## Expected behavior (Required)
altar should work

## Server Log / Error Report
(https://pastebin.com/5HEa19Ab)

## Server specs (Required)

 - Server Software: This server is running Paper version git-Paper-155 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 99cf01f)
 - Minecraft Version: 1.18.1

## FULL plugins list (Required)
AdvancedPortals, ajParkour, ArmorStandTools, AuctionHouse, AuthMe, bAnnouncer*, BlockParticles, ClickSort, CMILib, CoreProtect, dynmap, Dynmap-WorldGuard*, DynMap_Residence, EpicReplant, Essentials, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, ExoticGarden, ExtraGear, FakaHedaMinequery, FluffyMachines, GMusic, GSit, HolographicDisplays, InventoryRollbackPlus, Jobs, JumpPads, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MyCommand, MythicMobs, PlaceholderAPI, PlayTime*, PrivateStorage, ProtocolLib, Residence, SignShop, SkinsRestorer, sleep-most, Slimefun, SoulJars, TAB, TNTRun_reloaded, UberEnchant, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldSpawn*

**Comment by TheBusyBiscuit** [comment]
This is the "dough" issue tracker, I think you are looking for the Residence issues tracker:
https://github.com/Zrips/Residence/issues

**Comment by misuda12** [comment]
Why dought had to change registerModule(Server, ...) to registerModule(PluginManager, ...) where it basically is doing the same, you are still retriving the plugin via Server interface. Can't you add backward support for Server too ?
Zrips had not respond to any issue ever.
