### ISSUE TITLE
get block position y doesnt work when y < 0

### ISSUE THREAD

**Issue by ybw0014** [baked-libs/dough#162]
## Description (Required)

DynaTech uses BlockPosition to store the blocks, and as mc 1.18 comes out, the world's minimum height becomes -64 instead of 0.
When Dynatech is trying to get block from BlockPosition with y < 0, it will raise an error:  
`java.lang.IllegalArgumentException: y out of range (expected -64-320, got 4045)`

## Steps to reproduce the Issue (Required)

1. Place water mill or water turbine from DynaTech underground (y < 0).

## Expected behavior (Required)

`BlockPosition#getY()` should return correct value for y < 0.

## Server Log / Error Report

https://pastebin.com/zvLniqi5

## Server specs (Required)

 - Server Software: paper 216
 - Minecraft Version: 1.18.1

## FULL plugins list (Required)

```
  + Slimefun DEV - 1008 (git 020094e0)
  + WhatIsThis 4.7
  + DynaTech DEV - 160 (git e1075a1c)
  + Vault 1.7.2-b107
  + ProtocolLib 4.7.0
  + Networks DEV - 33 (git 3474aec2)
  + SfItemsExporter 1.1
  + SlimeTinker DEV - 71 (git a226bf46)
```

**Comment by ybw0014** [comment]
Can confirm this also happens when using Realization Altar from Crystamae Historia.

**Comment by Sfiguz7** [comment]
I believe this was fixed by the PR above.
