### ISSUE TITLE
Incompatiblity with newest Lands Plugin (6.26.2)

### ISSUE THREAD

**Issue by oORevanOo** [baked-libs/dough#197]
## Description (Required)
Newest version of Lands 6.26.2 throws this error: https://pastebin.com/2PyPKH3v

## Server specs (Required)
Purpur 1.19.2
Slimefun 1035
Lands 6.26.2

**Comment by Angeschossen** [comment]
Looking into this.

**Comment by Angeschossen** [comment]
Fixed in next v. of Lands. I just added backwards support. This can be closed.

**Comment by oORevanOo** [comment]
Thank you!

**Comment by oORevanOo** [comment]
Sadly, issue still persists

**Comment by Angeschossen** [comment]
should be solved now.

**Comment by oORevanOo** [comment]
thanks again :)

**Comment by oORevanOo** [comment]
Right as I was closing this, I noticed that you now can't access slimefun machines in the claimed Land

Breaking and placing these works, just not accessing them

**Comment by Angeschossen** [comment]
That sounds like your role is not allowed to interact with containers in the claimed land. You might want to check that in the menu.

**Comment by oORevanOo** [comment]
Even as the land owner?

**Comment by Angeschossen** [comment]
> Even as the land owner?

Depending on your config, yes.

**Comment by oORevanOo** [comment]
I have no idea which flag I should use
owner has all flags lands gave me, even with op rights, I have no permission (lands bypass)

**Comment by Angeschossen** [comment]
re-download latest.

**Comment by oORevanOo** [comment]
Seems like it's now really really really fixed
