### ISSUE TITLE
dough with Slimefun4 error

### ISSUE THREAD

**Issue by TsubakiDev** [baked-libs/dough#224]
## Description (Required)
When the Slimefun4 plug-in equipped with dough is run on the 1.20.2 server, a problem pops up

## Steps to reproduce the Issue (Required)
![image](https://github.com/baked-libs/dough/assets/132794625/90fcc66b-48d3-4c50-97b8-d0c3977bd536)

## Expected behavior (Required)
Just ran Slimefun4 on the 1.20.2 server

## Server Log / Error Report
https://pastes.dev/0GgOGyYnkw

## Server specs (Required)
git-Purpur-2067 (MC: 1.20.2)

 - Server Software: Purpur
 - Minecraft Version: 1.20.2

## FULL plugins list (Required)
spark, Slimefun

**Comment by J3fftw1** [comment]
This issue is related to https://github.com/PaperMC/Paper/pull/9770
