### ISSUE TITLE
Lands 

### ISSUE THREAD

**Issue by Angeschossen** [baked-libs/dough#75]
## Description (Required)
Is there any way to pass the actual plugin that uses dough, to the constructor of the Lands integration class in the protection module? It requires this, for flags etc.

https://github.com/baked-libs/dough/blob/fc572efd6c0042310156bba7d9f4516c8406c926/dough-protection/src/main/java/io/github/bakedlibs/dough/protection/ProtectionManager.java#L72

Here is the actual problem:
plugin = Lands, but it should be = plugin that uses dough
https://github.com/baked-libs/dough/blob/fc572efd6c0042310156bba7d9f4516c8406c926/dough-protection/src/main/java/io/github/bakedlibs/dough/protection/modules/LandsProtectionModule.java#L34

I haven't looked through the complete repo, but maybe passing the actual plugin to the constructor of the protection module manager would be an idea?

**Comment by WalshyDev** [comment]
Yeah, that is a good idea. Not exactly sure why it's done this way currently

**Comment by Angeschossen** [comment]
Any update on this? Should I open a PR?

**Comment by J3fftw1** [comment]
Yea you can open a pr

**Comment by WalshyDev** [comment]
Fix has been merged
