### ISSUE TITLE
OBC class not found

### ISSUE THREAD

**Issue by variananora** [baked-libs/dough#76]
## Description (Required)

Just found this on bootup on Slimefun RC-27.
Walshy told me to report it.

## Steps to reproduce the Issue (Required)

1. Build RC-27
2. Start a server using it

## Expected behavior (Required)

It doesn't error

## Server Log / Error Report

Server logs: https://haste.zneix.eu/oqamuvyxyv.yaml

Other error logs: https://haste.zneix.eu/padasivoka.properties
(idk about this one, i forgot what i did)

## Server specs (Required)

 - Server Software: Paper-238
 - Minecraft Version: 1.17.1

## FULL plugins list (Required)

```
> pl
[23:11:37 INFO]: Plugins (1): Slimefun
```

**Comment by Seggan** [comment]
I suggest fixing this before the builds unfreeze, SFCalc is broken because of it

**Comment by TheBusyBiscuit** [comment]
This was already fixed in #67
